import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df1 = pd.read_csv(r"C:\Users\HP\Downloads\archive (3)\Unemployment in India.csv")
df2 = pd.read_csv(r"C:\Users\HP\Downloads\archive (3)\Unemployment_Rate_upto_11_2020.csv")
df = pd.concat([df1, df2], ignore_index=True)
df.columns = df.columns.str.strip()
print("Columns in combined DataFrame:", df.columns.tolist())
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors='coerce')
df["Estimated Unemployment Rate (%)"] = pd.to_numeric(df["Estimated Unemployment Rate (%)"], errors='coerce')
df["Estimated Employed"] = pd.to_numeric(df["Estimated Employed"], errors='coerce')
df["Estimated Labour Participation Rate (%)"] = pd.to_numeric(df["Estimated Labour Participation Rate (%)"], errors='coerce')
print("\nDataset Info:")
print(df.info())
print("\nSummary Stats:")
print(df.describe())
plt.figure(figsize=(12,6))
sns.lineplot(data=df, x="Date", y="Estimated Unemployment Rate (%)", hue="Region")
plt.title("Unemployment Rate Over Time by Region")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,6))
sns.lineplot(data=df, x="Date", y="Estimated Labour Participation Rate (%)", hue="Region")
plt.title("Labour Participation Rate Over Time by Region")
plt.xlabel("Date")
plt.ylabel("Labour Participation Rate (%)")
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
pre_covid = df[df["Date"] < "2020-03-01"]
during_covid = df[df["Date"] >= "2020-03-01"]
plt.figure(figsize=(10,5))
sns.kdeplot(pre_covid["Estimated Unemployment Rate (%)"], label="Pre-COVID", fill=True)
sns.kdeplot(during_covid["Estimated Unemployment Rate (%)"], label="During-COVID", fill=True)
plt.title("Unemployment Rate Distribution: Pre vs During COVID")
plt.xlabel("Unemployment Rate (%)")
plt.legend()
plt.show()
avg_unemp = df.groupby("Region")["Estimated Unemployment Rate (%)"].mean().sort_values()
plt.figure(figsize=(10,6))
sns.barplot(x=avg_unemp.values, y=avg_unemp.index, palette="viridis")
plt.title("Average Unemployment Rate by Region")
plt.xlabel("Average Unemployment Rate (%)")
plt.ylabel("Region")
plt.tight_layout()
plt.show()